version: '3.6'
services:
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 7000:8080
    restart: always
    volumes:
      - './swagger.json:/swagger.json'
    environment:
      SWAGGER_JSON: ${SWAGGER_JSON}
  metrics:
    image: 'prom/prometheus:latest'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    ports: 
        - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
